### ISSUE TITLE
装扮烟火大会相关表情

### ISSUE THREAD

**Issue by lrhtony** [lrhtony/bilibili_emoji#1]
目前缺少装扮烟火大会的欧皇、沙茶兔、抹茶狗、小红眼，如果有以上表情的可进行回复

**Comment by lrhtony** [comment]
目前已收集齐除沙茶兔以外的表情。关于沙茶兔的表情在活动界面不存在，也没有相关用户发布沙茶兔相关的内容，故无法得知该表情如何获得，暂且不理会

**Comment by vcheckzen** [comment]
分享两个接口，不过只能看到免费和自己买过的表情

http://api.bilibili.com/x/v2/reply/emojis
http://api.bilibili.com/x/emote/user/panel/web?business=reply
